name: NodeJs with Webpack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Copy build files to Nginx directory
      run: |
        sudo cp -r build/* /var/www/html/
      if: success()

    - name: Restart Nginx
      run: |
        sudo systemctl restart nginx
      if: success()
